sudo: required
services:
  - docker

before_install:
  - docker build -t marutp/docker-reactapp -f Dockerfile.dev . 

script:
  - docker run marutp/docker-reactapp npm run test   -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-reactapp
  env: DockerReactapp-env
  bucket_name: elasticbeanstalk-us-east-1-602002819079
  bucket_path: docker-reactapp
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"    