# Specify a base image
FROM node:alpine

WORKDIR '/app'

# Install some pdendencies

COPY package.json .

# Install some pdendencies

RUN npm install

#COPY . .

# Default command

CMD ["npm","run","start"]